blog/urls.py
from django.urls import path
from .views import *
app_name='blog'

urlpatterns=[
    path('',BlogListView.as_view(), name='home'),
    path('create/',CreateBlogView.as_view(), name='create'),
    path('delete/<int:pk>/',DeleteBlogView.as_view(),name='delete'),
    path('update/<int:pk>/',BlogUpdateView.as_view(), name='update'),
    path('post/<slug:post>/<int:pk>/',post_detail,name='detail'),
    path('<int:post_id>/comment/',post_comment, name='post_comment'),
    

]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

users/urls.py
from django.urls import path 
from .views import *

app_name='users'
urlpatterns=[
    path('login/',sign_in, name='login'),
    path('logout/',sign_out, name='logout'),
    path('reg/',sign_up, name='register'),
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
class Post(models.Model):
    title=models.CharField(max_length=200)
    image=models.ImageField(upload_to='image',blank=True,null=True)
    content=models.TextField()
    author=models.ForeignKey('auth.User',on_delete=models.CASCADE)
    published_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    slug=models.SlugField(max_length=200,default='',blank=True)
    class Meta:
        ordering=['-published_at']
    
    
    def save(self,*args,**kwargs):
        self.slug=slugify(self.title)
        super().save(*args,**kwargs)
    
    def get_absolute_url(self):
        return reverse('blog:detail',args=[self.slug,self.id])

    def __str__(self):
        return f'{self.title}'
    
class Comment(models.Model):
    post=models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    body=models.TextField()
    blog_author=models.ForeignKey('self',on_delete=models.CASCADE, null=True, blank=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    is_active=models.BooleanField(default=True)

    class Meta:
        ordering=['created']
        indexes=[
            models.Index(fields=['created']),
            ]

    def __str__(self):
        return f'comment by {self.name} on {self.post}'
   
#    get all replies by blog author
    def get_replies(self):
        return Comment.objects.filter(blog_author=self)

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post,Comment

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','image','content',]
        # widget={
        #     'title':forms.TextInput(attrs={
        #         'class':'mb-2 w-full px-4 py-3 rounded-xl'
        #     }),
        #     'image':forms.ClearableFileInput(attrs={
        #         'class':'w-full py-3 px-4 border rounded'
        #     }),
        #     'content':forms.Textarea(attrs={
        #         'class':'w-full h-32 p-2 border rounded'
        #     }),
        # 
    title=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Write a nice title for your content ',
        'class':'w-full px-4 py-3 rounded-lg border border-gray-500'
    }))
    image=forms.ImageField(widget=forms.ClearableFileInput(attrs={
        'class':'w-full py-3 px-4 border border-gray-500 rounded'
    }))
    content=forms.CharField(widget=forms.Textarea(attrs={
        'placeholder':'write your creative thoughts here...',
        'class':'border border-gray-500 rounded-lg h-48 w-full p-2'
    }))


class CommentForm(ModelForm):
    class Meta:
        model=Comment
        fields=['body']
        widgets={
            'body':forms.Textarea(attrs={
                'placehodler':'Comment here.....',
                'class':'px-6 py-4 h-32 w-full rounded-lg border border-gray-600'
            })
        }

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .models import Post
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import PostForm, CommentForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
class BlogListView(ListView):
    model=Post
    template_name='blog/index.html'
    context_object_name='posts'


# class BlogDetailView(LoginRequiredMixin,DetailView):
#     model=Post
#     template_name='blog/post_detail.html'
@login_required   
def post_detail(request,post,pk):
    post=get_object_or_404(Post, pk=pk, slug=post)
    comments=post.comments.filter(is_active=True)
    form=CommentForm()
    return render(request,'blog/post_detail.html',{'post':post,'comments':comments,'form':form})

class CreateBlogView(LoginRequiredMixin,CreateView):
    form_class=PostForm
    template_name='blog/create.html'
   
    def form_valid(self, form):
        form.instance.author=self.request.user
        messages.success(self.request,'The post was created successfully')
        return super(CreateBlogView,self).form_valid(form)

class BlogUpdateView(LoginRequiredMixin,UpdateView):
    model=Post
    form_class=PostForm
    template_name='blog/update_post.html'
    # success_url=reverse_lazy('blog:home')

    def form_valid(self,form):
        messages.success(self.request,"The post was updated successfully")
        return super(BlogUpdateView,self).form_valid(form)

class DeleteBlogView(LoginRequiredMixin,DeleteView):
    model=Post
    template_name='blog/delete_post.html'
    success_url=reverse_lazy('blog:home')

    def form_valid(self,form):
        messages.success(self.request,'The post has been deleted successfully')
        return super(DeleteBlogView,self).form_valid(form)
    
@login_required
@require_POST
def post_comment(request, post_id):
    post=get_object_or_404(Post, id=post_id)
    comment=None
    form=CommentForm(data=request.POST)
    if form.is_valid():
        comment=form.save(commit=False)
        comment.post=post
        comment.name=request.user.username
        comment.save()
    return render(request,'blog/comment.html',{'post':post,'form':form,'comment':comment})

blog/templates/blog/base.html
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title%}{% endblock%} | Blog
    </title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://kit.fontawesome.com/a0e99f8a3c.js" crossorigin="anonymous"></script>
</head>
<body class="min-h-screen">
    <header class="bg-gray-100 sticky top-0 z-10 border-b border-gray-200 p-6">
        <nav class="max-w-4xl mx-auto flex justify-between items-center ">
              <div class="text-2xl sm:text-3xl">
                <a href="/" class="">DjangoBlog</a>
              </div>
              <button id="toggleButton" class="relative h-8 w-8 cursor-pointer text-3xl md:hidden ">
                <div
            class="absolute top-4 -mt-0.5 h-1 w-8 rounded bg-black transition-all duration-500 before:absolute before:h-1 before:w-8 before:-translate-x-4 before:-translate-y-3 before:rounded before:bg-black before:transition-all before:duration-500 before:content-[''] after:absolute after:h-1 after:w-8 after:-translate-x-4 after:translate-y-3 after:rounded after:bg-black after:transition-all after:duration-500 after:content-['']">
          </div>
              </button>
              <div class="space-x-6 hidden sm:block">
                  {% if request.user.is_authenticated %}
                <a href="{% url 'blog:create' %}" class="border-2 border-green-500 rounded-xl bg-white text-black hover:text-gray-500 px-6 py-3  text-xl font-semibold ">Create</a>
                <a href="{% url 'users:logout' %}" class="text-xl font-semibold  text-slate-800 hover:text-slate-500">Logout</a>
                {% else %}
            
                <a href="{% url 'users:login' %}" class="text-xl font-semibold  text-slate-800 hover:text-slate-500">Login</a>
                <a href="{% url 'users:register' %}" class="border-2 border-green-500 bg-white rounded-lg py-3 px-6  text-xl text-black hover:text-gray-500 font-semibold">register</a>
                 {% endif %}
              </div>
        </nav>
        <!-- mobile menu -->
        <section id="section" class="right-0 top-70 justify-content-center origin-top absolute hidden w-full text-white flex-col bg-black text-5xl">
          <!-- <button id="close" class="text-8xl self-end px-6">
            &times;
        </button> -->
          <div class="space-y-6 flex min-h-screen flex-col items-center py-8">
            {% if request.user.is_authenticated %}
          <a href="{% url 'blog:create' %}" class="  w-full py-6 text-center hover:opacity-90 ">Create</a>
          <a href="{% url 'users:logout' %}" class="w-full py-6 text-center hover:opacity-90">Logout</a>
          {% else %}
            
      
          <a href="{% url 'users:login' %}" class=" w-full py-6 text-center hover:opacity-90">Login</a>
          <a href="{% url 'users:register' %}" class="   w-full py-6 text-center hover:opacity-90">register</a>
          {% endif %}
        </div>
        </section>
    </header>
    
    <main class="widescreen:section-min-height tallscreen:section-min-height ">
      
        <div class="max-w-sm mx-auto p-2">
          {% if messages %}
          {% for message in messages %}
          <div class="flex flex-col max-w-lg  mx-auto">
              <div class="flex inline-flex justify-between bg-teal-100 border border-teal-400 text-teal-700 px-4 py-3 my-2 rounded "
                  role="alert">
                  <span class="block sm:inline pl-2">
                      <strong class="font-bold"> {{message}}</strong>
                  </span>
                  <span class="inline" onclick="return this.parentNode.remove();">
                      <svg class="fill-current h-6 w-6" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                          <title>Close</title>
                          <path
                              d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z" />
                      </svg>
                  </span>
              </div>
              </div>
            {% endfor %}
            {% endif %}
          </div>
          {% comment %}
          <div class="bg-slate-200 rounded-lg border sm:w-10 w-full">
            <h3>Most Commented Post</h3>
            {% get_most_commented_post as most_commented_post %}
            {% for post in most_commented_post %}
            <li>
                <a href="{{post.get_absolute_url}}" class="">{{post.title}}</a>
            </li>
            {% endfor %}
          </div>
          {% endcomment %}
        {% block content %}
        {% endblock %}
    </main>
    <footer class="bg-gray-100 p-2">
        <div class="max-w-4xl mx-auto p-6 space-x-6 flex flex-col justify-between items-center sm:flex-row">
            <div class="w-full sm:w-1/2">
                <h2 class="text-3xl font-semibold">DjangoBlog</h2>
                <p class=" text-lg text-slate-800 font-extralight">
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Animi nam tempore voluptate exercitationem asperiores laborum enim fugit ducimus maxime natus.
                </p>
            </div>
            <div class="sm:w-1/2 w-full flex flex-col sm:flex-row justify-between">
                <div class="w-full mb-2">
                    <h2 class="text-2xl font-semibold">Useful Links</h2>
                    <div class="space-y-2 flex flex-col items-start ">
                        <a href="" class="text-xl text-slate-800 hover:text-slate-500">About</a>
                        <a href="" class="text-xl text-slate-800 hover:text-slate-500">Contact</a>
                        <a href="" class="text-xl text-slate-800 hover:text-slate-500">Location</a>
                        <a href="" class="text-xl text-slate-800 hover:text-slate-500">Privacy policy</a>
                    </div>
                </div>
                <div class="w-full mb-2">
                    <h2 class=" text-2xl font-semibold">Socials</h2>
                    <div class=" space-x-2">
                        <a href="" class=""><i class="fa-brands fa-x-twitter bg-blue-700 text-white  rounded-full p-2"></i></a>
                        <a href="" class=" "><i class="fa-brands fa-facebook bg-blue-500 rounded-full text-white p-2"></i></a>
                        <a href="" class=""><i class="fa-brands fa-youtube bg-red-500 rounded-full   p-2 text-white"></i></a>
                    </div>
                    <div class="">
                        <h2 class="text-2xl font-semibold">Address</h2>
                        <address>
                            Nairobi<br>
                            P.O Box-35511<br>
                            DreamLand Street Avenue
                        </address>
                    </div>
                </div>
          
            </div>
            
            
            
        </div>
        <p class="text-lg text-base text-center">&copy; DjangoBlog<span id="demo" class=""></span> | All rights reserved</p>
    </footer>
    {% load static %} 
    <script src="{% static '/js/main.js' %}"></script>
</body>
</html>

blog/templates/blog/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    {% if comment %}
    <div class="max-w-md mx-auto bg-white rounded-lg shadow-2xl p-6">
        <div class="my-10">
            <h2 class="text-3xl my-6">Your comment has been added.</h2>
        <a href="{{post.get_absolute_url}}" class="bg-blue-600 hover:bg-blue-700 text-white rounded-lg px-6 py-4">Back to the post</a>
        </div>
    </div>
    {% else %}
    {% include 'blog/comment_form.html' %}
    {% endif %} 
</body>
</html>

blog/templates/blog/comment_form.html
<div class="max-w-xl mx-auto shadow-2xl bg-white p-6 rounded-lg">
    <h2 class="text-4xl font-semibold text-center text-gray-800">Add a new Comment</h2>
    <form action="{% url 'blog:post_comment' post.id %}" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3">
            <label for="" class="text-xl font-semibold">{{field.label_tag}}</label>
            {{field}}
        </div>
        {% endfor %}
        <input type="submit" value="Add comment" class="bg-blue-600 hover:bg-blue-700 text-white rounded-lg px-6 py-4">
    </form>
</div>

blog/templates/blog/create.html
{% extends 'blog/base.html' %}

{% block title%} Create {% endblock %}

{% block content %}

<div class="max-w-md mx-auto p-6 shadow-2xl m-4 ">
  <h2 class="font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-blue-500 text-3xl text-center">Create blog</h2>
  <form action="{{object.get_absolute_url}}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <label for="" class="text-2xl font-semibold">{{field.label_tag}}</label>
      {{field}}
      {% endfor %}
    <input type="submit" value="Create" class="w-full px-6 py-3 rounded-xl border bg-teal-500 hover:bg-teal-700 text-white font-semibold">
  </form>
</div>
              
{% endblock %}

blog/templates/blog/delete_post.html
{% extends 'blog/base.html' %}

{% block title %}
{{object.title }}

{% endblock %}
{% block content %}
<div class="max-w-4xl mx-auto p-6 rounded-xl m-4 shadow">
    <form action="." method="post">
        {% csrf_token %}
    <p class="text-xl font-medium">Are you sure you want to delete <span class="text-2xl font-bold">"{{object.title}}"</span ></p>
        {% if object.image %}
        <img src="{{object.image.url}}" alt="{{object.title}}" class="w-full h-64 mb-4  rounded-xl object-cover object-center">
            {% endif %}
        <input type="submit" value="Delete" class="bg-red-500 px-6 py-4 rounded-xl hover:bg-red-700 text-white font-semibold">
    <a href="{{post.get_absolute_url}}" class="bg-blue-500 hover:bg-blue-700 rounded-xl px-6 py-4 text-white font-semibold">Cancel</a>
    </form>
</div>


{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
 <section class="container max-w-4xl mx-auto  ">
        <div class="relative ">
            {% load static %}
            <img src="{% static '/image/header.jpg' %}" alt="header image" class="object-center object-cover opacity-60 ">
            <div class="absolute bottom-0 left-0 right-0 top-0 h-full w-full text-3xl text-center overflow-hidden ">
                <div class="h-full flex items-center justify-center flex-col">
                    <p class="sm:text-6xl text-4xl text-slate-800  font-bold">Welcome to <span class="text-indigo-500 ">DjangoBlog</span> </p>
                    <p class="text-2xl font-medium text-slate-800 ">Exploring Ideas, Insights, and Inspiration....</p>
                </div>
               
            </div>
            
        </div>
 </section>
 <div class="max-w-4xl mx-auto flex justify-start items-center m-2 flex-col w-full">
    <h2 class="text-3xl font-semibold">Recent Blogs</h2>
 <hr class="border-t border-gray-500 my-4 w-20">
 </div>
  <div class="max-w-4xl mx-auto grid grid-rows-1 sm:grid-cols-3 gap-3 px-6 py-12 bg-gray-100">
    {% if posts %}
    {% for post in posts %}  
 <div class="max-w-sm  bg-white border border-gray-200 rounded-lg shadow ">
     <a href="{{post.get_absolute_url}}">
         {% if post.image %}
         <img class="rounded-t-lg h-64 w-full sm:w-96 object-cover object-center hover:opacity-75 transition-opacity duration-500 ease-in-out" src="{{post.image.url }}" alt="{{post.title}}" />
         {% endif %}
     </a>
     <div class="p-5">
         <a href="{{post.get_absolute_url}}">
      <h5 class="mb-2 text-2xl  font-bold tracking-tight text-gray-900 "> {{post.title}}</h5>
         </a>
         <p class="mb-3 font-normal text-gray-700 line-clamp-2 "> {{post.content}}</p>
         <a href="{{post.get_absolute_url}}" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700">
             Read more
              <svg class="w-3.5 h-3.5 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                 <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
             </svg>
         </a>
     </div>
 </div>
   {% endfor %}
   {% endif %}
  </div>
  
{% endblock %}

blog/templates/blog/latest_post.html
{% extends 'blog/base.html'%}
{% block content %}
{% for post in latest_post %}
<p class="text-xl"><a href="{{post.get_absolute_url}}">{{post.title}}</a></p>
{% endfor %}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %} {{post.title}} {% endblock %}


{% block content %}
<div class="max-w-4xl mx-auto py-12 px-6  shadow">
    <div class="p-6">
        <h2 class="text-4xl font-semibold">{{post.title}}</h2>
        <hr class="border-t border-gray-300 my-4 w-1/4">
        <p>published by <span class="font-medium">{{post.author|title}}</span> on <span class="font-medium">{{post.published_at | date:"M d, Y"}}</span></p>

        {% if post.image %}
        <img src="{{post.image.url}}" alt="{{post.title}}" class="object-center object-cover h-80 w-full rounded-xl ">
        {% endif  %}
        <p class="first-letter:text-6xl first-letter:font-bold text-lg block">{{post.content}}</p>
        <div class="flex justify-between items-center flex-col sm:flex-row">
            <a href="{% url 'blog:home' %}" class=" my-4 inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                <svg class="w-6 h-6 text-white m-1 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5H1m0 0 4 4M1 5l4-4"/>
                  </svg>
                Go back
                 
            </a>
           <div class="">
            {% if request.user == post.author %}
            <a href="{% url 'blog:update' post.pk  %}" class="my-4 inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-teal-500 rounded-lg hover:bg-teal-800 focus:ring-4 focus:outline-none focus:ring-teal-300 dark:bg-teal-600 dark:hover:bg-teal-700 dark:focus:ring-teal-800">Update</a>
            <a href="{% url 'blog:delete' post.pk  %}" class="my-4 inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-red-500 rounded-lg hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">Delete</a>
            {% endif %}
           </div>
        </div>
    </div>
    <div class="max-w-xl mx-auto bg-white rounded-lg shadow-2xl p-8">
        {% with comments.count as total_comments %}
        <h3 class="text-gray-500 font-medium">{{total_comments}} comment{{total_comments|pluralize}}</h3>
        {% endwith %}
        <hr class="border border-gray-600 w-full mx-auto">
        {% for comment in comments %}
        <div class="bg-gray-100 rounded-lg shadow px-6 py-4 w-full m-4">
            <p class="text-sm">Comment {{forloop.counter}} by {{comment.name}} {{comment.created}}</p>
            <p class="text-xl text-gray-600 font-light">
                {{comment.body|linebreaks}}
            </p>
        </div>
        {% empty %}
        <p class="text-3xl text-gray-600 font-semibold">There are no comments.</p>
        {% endfor %}
        {% include 'blog/comment_form.html' %}
    </div>
    
</div>

{% endblock %}

blog/templates/blog/update_post.html
{% extends 'blog/base.html' %}

{% block title %}
  {{object.title }}
{% endblock %}

{% block content %}
<div class="max-w-sm m-4 mx-auto p-6 rounded-xl shadow-2xl">
  <h2 class="text-3xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-green-500 to-teal-500 text-center">Update Blog</h2>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <label for="" class="text-xl font-semibold block w-full mb-2">{{field.label_tag}}</label>
    {{field}}
    {% endfor%}
    <input type="submit" value="Update" class="mt-2 px-6 py-4 rounded-xl w-full bg-teal-500 hover:bg-teal-700 text-white font-semibold">

 </form>
 <div class="w-full mt-6 flex items-center justify-center">
  <a href="{{post.get_absolute_url}}" class="px-6 py-4 text-center rounded-xl w-full bg-red-500 hover:bg-red-700 text-white font-semibold">Cancel</a>

 </div>
</div>

{% endblock %}